version: '3.9'

services:
  mysql:
    container_name: "bonus-service-mysql"
    image: mysql:latest
    hostname: "bonus-service-mysql"
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bonus_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
    volumes:
      - "data:/var/lib/mysql"
volumes:
  data:
